# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PygeoapiConfig
                                 A QGIS plugin
 Update pygeoapi configuration file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-16
        copyright            : (C) 2025 by ByteRoad
        email                : info@byteroad.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PygeoapiConfig class from file PygeoapiConfig.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pygeoapi_config import PygeoapiConfig
    return PygeoapiConfig(iface)
