name: Build and Attach Plugin ZIP to Release (Windows)

on:
  release:
    types: [published]
  pull_request: 

jobs:
  package-and-upload:
    if: github.event_name == 'release'
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pb_tool
        run: |
          pip install pb_tool==3.1.0

      - name: Run pb_tool zip
        run: |
          pb_tool zip

      - name: Copy zip file to staging directory
        run: |
          New-Item -ItemType Directory -Path build -Force
          Copy-Item zip_build\*.zip build\

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-on-pr: 
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest annotation plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Run unit tests
        run: |
          pytest -q