name: Run unit tests on PR branch

on:
  pull_request: 

jobs:
  test-on-pr: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run tests in virtual display
        run: |
          xvfb-run -a python -m pytest --import-mode=importlib